# Generated by Django 6.0.4 on 2026-04-21 18:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguradora', '0002_criar_grupos_perfil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf_cnpj', models.CharField(blank=True, max_length=18, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{11}$|^[0-9]{14}$', 'CPF deve ter 11 dígitos, CNPJ 14 dígitos')], verbose_name='CPF/CNPJ')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
